const SET_BY_GENRES = "SET_BY_GENRES";
const SET_MOVIE_GENRES = "SET_MOVIE_GENRES";
const SET_POPULAR_MOVIES = "SET_POPULAR_MOVIES";
const SET_TOP_5_POPULAR_MOVIES = "SET_TOP_5_POPULAR_MOVIES";

const types = {
  SET_BY_GENRES,
  SET_MOVIE_GENRES,
  SET_POPULAR_MOVIES,
  SET_TOP_5_POPULAR_MOVIES,
};

export default types;
